
trigger: none


pool: vamika

variables: 
  backendsc: 'ammupipeline' 
 
steps:
- task: TerraformInstaller@1
  displayName: terraform install
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: $(backendsc)
    backendAzureRmStorageAccountName: 'shahedstg490'
    backendAzureRmContainerName: 'shahed-tfstate'
    backendAzureRmKey: madhuri
- task: TerraformTask@5
  displayName: terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: $(backendsc)

- task: TerraformTask@5
  displayName: terraform apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: $(backendsc)
