
trigger: none


pool: vamika
  
steps:
- task: TerraformInstaller@1
  displayName: terraform install
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'ammupipeline'
    backendAzureRmStorageAccountName: 'shahedstg490'
    backendAzureRmContainerName: 'shahed-tfstate'
    backendAzureRmKey: 'maddy.tfstate'
- task: TerraformTask@5
  displayName: terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'ammupipeline'

- task: TerraformTask@5
  displayName: terraform apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'ammupipeline'
